  version: '3.8'

  services:
    influxdb2:
      container_name: influxdb2
      image: influxdb:2
      ports:
        - "8086:8086"
      volumes:
        - ./influxdb2-data:/var/lib/influxdb2
        - ./influxdb2-config:/etc/influxdb2
      env_file:   
        - influxv2.env

    telegraf:
      container_name: telegraf
      image: telegraf:alpine
      depends_on:
        - influxdb2
      volumes:
        # Mount for telegraf config
        - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      env_file:
        - influxv2.env
    website-monitor:
      container_name: website-monitor
      image: ninjaasa/influxdb-getting-started-website-monitor:latest
      depends_on:
        - influxdb2
      env_file:
        - monitor.env

    # website-monitor:
    #   container_name: website-monitor
    #   build:
    #     context: ./monitor-web-server
    #     dockerfile: Dockerfile
    #   depends_on:
    #     - influxdb2
    #   env_file:
    #     - monitor.env
