  version: '3.8'

  services:
    influxdb2:
      container_name: influxdb2
      image: influxdb:2
      ports:
        - "8086:8086"
      volumes:
        - ./influxdb2-data:/var/lib/influxdb2
        - ./influxdb2-config:/etc/influxdb2
      environment:
        DOCKER_INFLUXDB_INIT_MODE: setup
        DOCKER_INFLUXDB_INIT_USERNAME: ${MYUSERNAME}
        DOCKER_INFLUXDB_INIT_PASSWORD: ${MYPASSWORD}
        DOCKER_INFLUXDB_INIT_ORG: ${MYORGNAME}
        DOCKER_INFLUXDB_INIT_BUCKET: ${MYBUCKETNAME}