name: Website Monitor - Publish Docker Image
on:
  push:
    branches: [ "main" ]

jobs:
  build-and-validate:
    name: Build and Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -t my-image:latest .

      - name: Validate
        run: |
          wget https://github.com/opencontainers/image-tools/releases/download/v1.0.0/oci-image-tool && \
          chmod +x oci-image-tool && \
          ./oci-image-tool validate --tarball my-image.tar.gz

  push_to_registry:
    name: Push Docker Image to Docker Hub
    needs: build-and-validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
      - name: Build version
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H:%M:%SZ')"
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ninjaasa/influxdb-getting-started-website-monitor
          tags: |
            type=raw,value=${{ steps.date.outputs.date }}
            type=raw,value=latest
          labels: |
            org.label-schema.build-date=${{ steps.date.outputs.date}}
            org.opencontainers.image.created=${{ steps.date.outputs.date}}
      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ./webmonitor
          file: ./webmonitor/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}          
              
